name = "spotvault"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
NODE_VERSION = "v22.14.0"
NEXT_PUBLIC_SERVER_URL = "https://spotvault.pages.dev"